baseURL = 'https://316140221.github.io/Hugo'
defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = true
title = 'Insignificant Universe'
theme = 'custom'

[pagination]
  pagerSize = 10

[params]
  description = "Insignificant Universe"
  keywords = "新闻, 资讯, 聚合"
  author = "内容聚合站"

[languages]
  [languages.zh]
    languageCode = 'zh-CN'
    languageName = '中文'
    title = '无关紧要的宇宙'
    weight = 1
    [languages.zh.params]
      description = "自动化内容聚合网站 - 中文版"
      keywords = "新闻, 资讯, 聚合, 科技, 财经, 娱乐"
      author = "内容聚合站"
    
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Insignificant Universe'
    weight = 2
    [languages.en.params]
      description = "Automated Content Aggregation Website - English Version"
      keywords = "news, tech, finance, entertainment, aggregation"
      author = "Content Hub"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  # 中文菜单
  [[languages.zh.menu.main]]
    name = "首页"
    url = "/"
    weight = 10
  [[languages.zh.menu.main]]
    name = "科技"
    url = "/tech/"
    weight = 20
  [[languages.zh.menu.main]]
    name = "财经"
    url = "/finance/"
    weight = 30
  [[languages.zh.menu.main]]
    name = "娱乐"
    url = "/entertainment/"
    weight = 40
    
  # 英文菜单
  [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[languages.en.menu.main]]
    name = "Technology"
    url = "/tech/"
    weight = 20
  [[languages.en.menu.main]]
    name = "Finance"
    url = "/finance/"
    weight = 30
  [[languages.en.menu.main]]
    name = "Entertainment"
    url = "/entertainment/"
    weight = 40

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
